### ISSUE TITLE
Infinite xp glitch

### ISSUE THREAD

**Issue by iModyHK** [Mobius1/xperience#10]
I used this as in FAQ

`AddEventHandler('gameEventTriggered', function(event, data)
    if event == "CEventNetworkEntityDamage" then
        local victim      = tonumber(data[1])
        local attacker    = tonumber(data[2])
        local weaponHash  = tonumber(data[5])
        local meleeDamage = tonumber(data[10]) ~= 0 and true or false 

        -- Don't register melee damage
        if not meleeDamage then
            -- Check victim and attacker are both players
            if (IsEntityAPed(victim) and IsPedAPlayer(victim)) and (IsEntityAPed(attacker) and IsPedAPlayer(attacker)) then
                if attacker == PlayerPedId() then -- We are the attacker
                    exports.xperience:AddXP(100) -- Give player 100 xp for getting a hit
                end
            end
        end
    end
end) `

 whenever a player throws gas , same player gains infinite xp until he dies, this causes earning xp to fast. How can I make it ignore gas and tazer?

**Comment by Mobius1** [comment]
You'd need to filter out those weapon's hashes:

```lua
local weaponBlacklist = {
    [`WEAPON_BZGAS`] = true,
    [`WEAPON_STUNGUN`] = true,
    [`WEAPON_TRANQUILIZER`] = true,
    [`WEAPON_STUNGUN_MP`] = true,
}

AddEventHandler('gameEventTriggered', function(event, data)
    if event == "CEventNetworkEntityDamage" then
        local victim = tonumber(data[1])
        local attacker = tonumber(data[2])
        local weaponHash = tonumber(data[5])
        local meleeDamage = tonumber(data[10]) ~= 0 and true or false

        if not meleeDamage then -- Don't register melee damage
            if weaponBlacklist[weaponHash] == nil then -- Filter blacklisted weapons
                -- Check victim and attacker are both players
                if (IsEntityAPed(victim) and IsPedAPlayer(victim)) and (IsEntityAPed(attacker) and IsPedAPlayer(attacker)) then
                    if attacker == PlayerPedId() then -- We are the attacker
                        exports.xperience:AddXP(100) -- Give player 100 xp for getting a hit
                    end
                end
            end
        end
    end      
end)
```

**Comment by iModyHK** [comment]
How about IsEntityOnFire, it’s also gives them more xp 😖
