### ISSUE TITLE
UI not showing up / Can you update it please?

### ISSUE THREAD

**Issue by Gameadictive** [Mobius1/xperience#23]
So as a lot of people is stating.

**Comment by axdevelopment** [comment]
I think the resource is dead and won't be updated anymore, unfortunately :(

**Comment by Gameadictive** [comment]
> I think the resource is dead and won't be updated anymore, unfortunately :(

That´s so unlucky did u know any script with same things?

**Comment by axdevelopment** [comment]
I am using the old archive (esx_xp) and it works good, you just have to change the esx getsharedobject to the newest version

**Comment by Gameadictive** [comment]
Working like a charm, thanks.
